### ISSUE TITLE
add mb/itemlist

### ISSUE THREAD

**Issue by KewlSupaNewb** [Doc671/MarbleBot#2]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the feature**
I want whenever someone types "mb/itemlist" MarbleBot responds with https://docs.google.com/spreadsheets/d/1tKT8nFH4Aa1VkH_UeieoOkN_iBAfueZLqLOdHsVTJ1I/edit#gid=0

**Additional context**
melmon

**Comment by KewlSupaNewb** [comment]
what does the enhancement mean and what does self-assigned mean

**Comment by KewlSupaNewb** [comment]
;-; melmon respond to me

**Comment by Doc671** [comment]
Labels are defined here: https://github.com/Doc671/MarbleBot/labels

You can assign people to issues to work on them (but since I'm the only contributor I'm the only one who can be assigned issues).

Resolved with latest commit.
