### ISSUE TITLE
Signup Format Bug

### ISSUE THREAD

**Issue by ghost** [Doc671/MarbleBot#3]
**Describe the bug**
When I signup as **\*\\**, it breaks the text format into ***\**.

**To Reproduce**
1. Type `mb/race signup *\` **or** `mb/siege signup *\`
2. See the format bug `***`

![image](https://user-images.githubusercontent.com/41901404/62335849-a9311a00-b4f7-11e9-931a-3d8f88140b90.png)

**Additional**
When I signup as **\*\\\*\\**, it breaks the text format into ***\*\**.
When I signup as **\*\\\*\\\*\\**, it breaks the text format into ***\*\*\**.

The more **\*\\** you have, the more **star (\*)** you get! I don't know is it cool or not... but it looks funny so please fix!

![image](https://user-images.githubusercontent.com/41901404/62335889-db427c00-b4f7-11e9-9d8c-dc7a8a56fad8.png)

**Comment by Doc671** [comment]
Fixed with commit [3ba9650](https://github.com/Doc671/MarbleBot/commit/3ba96506212f102feee6687529205d06ecddaf8e).
