### ISSUE TITLE
mb/item bug

### ISSUE THREAD

**Issue by KewlSupaNewb** [Doc671/MarbleBot#4]
**Describe the bug**
The message "An error has occurred." appears when using the mb/item command for certain items.

**To Reproduce**
1. type mb/item (List of affected items: 85-89, 94, 95, 103)

**Expected behavior**
I expected to see the descriptions of said items.

**Screenshots**
https://cdn.discordapp.com/attachments/552349618281906179/633507665770840095/Screenshot_from_2019-10-14_20-32-34.png https://cdn.discordapp.com/attachments/552349618281906179/633507662000160774/Screenshot_from_2019-10-14_20-32-40.png https://cdn.discordapp.com/attachments/552349618281906179/633507661014630403/Screenshot_from_2019-10-14_20-32-44.png

**Additional context**
No other context.

**Comment by Doc671** [comment]
Resolved with commit [9b30c8f](https://github.com/Doc671/MarbleBot/commit/9b30c8f130135c4ba52482d34475b03f4acfc0a3).
